version: '3.8'

services:
  # Laravel PHP-FPM Service
  app:
    build:
      context: .
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-network
    depends_on:
      - db
    ports:
      - "9000:9000" # Expose PHP-FPM port to host

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_project_db
      MYSQL_USER: my_project_user
      MYSQL_PASSWORD: password
    networks:
      - laravel-network
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Nginx Web Server Service
  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    networks:
      - laravel-network
    depends_on:
      - app
    ports:
      - "80:80" # Expose Nginx to port 80 on the host machine

networks:
  laravel-network:
    driver: bridge

volumes:
  db_data:
    driver: local
