version: '3.8'

services:
  app:
    build:
      context: .
      args:
        APP_ENV: development
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
      - vendor_data:/var/www/vendor
    networks:
      - laravel-network
    depends_on:
      - db
    ports:
      - "9000:9000"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env.mysql
    volumes:
      - db_data:/var/lib/mysql
      # (optional) Mount a custom config file if needed:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel-network
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www:cached
      - vendor_data:/var/www/vendor
    networks:
      - laravel-network
    depends_on:
      - app
    ports:
      - "80:80"

networks:
  laravel-network:
    driver: bridge

volumes:
  db_data:
  vendor_data:
